apiVersion: v1
kind: Pod
metadata:
  name: no-vuln-ubuntu-2
  namespace: kube-system
spec:
  containers:
  - name: main
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
